import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import { env } from "@/lib/utils/env";
import { GoogleAnalytics } from "@/components/analytics/google-analytics";
import { Toaster } from "@/components/ui/sonner";
import { MazeSnippet } from "@/components/analytics/maze-snippet";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gaMeasurementId = env.analytics.gaMeasurementId;

  return (
    <html lang="ko">
      <body>
        {gaMeasurementId ? <GoogleAnalytics measurementId={gaMeasurementId} /> : null}
        <Providers>{children}</Providers>
        <Toaster />
        <MazeSnippet />
      </body>
    </html>
  );
}
