const PLACE_TYPE_TO_MIDDLE_CATEGORY: Record<string, string> = {
  restaurant: "식당",
  diner: "식당",
  food: "식당",
  korean_restaurant: "식당",
  chinese_restaurant: "식당",
  japanese_restaurant: "식당",
  sushi_restaurant: "식당",
  ramen_restaurant: "식당",
  thai_restaurant: "식당",
  vietnamese_restaurant: "식당",
  indian_restaurant: "식당",
  asian_restaurant: "식당",
  french_restaurant: "식당",
  italian_restaurant: "식당",
  spanish_restaurant: "식당",
  american_restaurant: "식당",
  mediterranean_restaurant: "식당",
  pizza_restaurant: "식당",
  hamburger_restaurant: "식당",
  bar_and_grill: "식당",
  sandwich_shop: "식당",
  deli: "식당",
  mexican_restaurant: "식당",
  brazilian_restaurant: "식당",
  turkish_restaurant: "식당",
  middle_eastern_restaurant: "식당",
  african_restaurant: "식당",
  steak_house: "식당",
  barbecue_restaurant: "식당",
  seafood_restaurant: "식당",
  vegan_restaurant: "식당",
  vegetarian_restaurant: "식당",
  fine_dining_restaurant: "식당",
  fast_food_restaurant: "식당",
  breakfast_restaurant: "식당",
  brunch_restaurant: "식당",
  buffet_restaurant: "식당",
  food_court: "식당",
  meal_takeaway: "식당",
  bar: "주점",
  pub: "주점",
  wine_bar: "주점",
  cafe: "카페",
  internet_cafe: "카페",
  coffee_shop: "카페",
  juice_shop: "카페",
  acai_shop: "카페",
  tea_house: "카페",
  cat_cafe: "카페",
  dog_cafe: "카페",
  bakery: "디저트",
  donut_shop: "디저트",
  bagel_shop: "디저트",
  dessert_shop: "디저트",
  dessert_restaurant: "디저트",
  ice_cream_shop: "디저트",
  confectionery: "디저트",
  chocolate_shop: "디저트",
  candy_store: "디저트",
  tourist_attraction: "관광명소",
  historical_place: "관광명소",
  historical_landmark: "관광명소",
  cultural_landmark: "관광명소",
  monument: "관광명소",
  museum: "관광명소",
  art_gallery: "관광명소",
  visitor_center: "관광명소",
  park: "공원",
  playground: "공원",
  national_park: "공원",
  state_park: "공원",
  dog_park: "공원",
  picnic_ground: "공원",
  observation_deck: "공원",
  plaza: "공원",
  beach: "자연",
  botanical_garden: "자연",
  garden: "자연",
  zoo: "자연",
  aquarium: "자연",
  church: "교회",
  mosque: "교회",
  hindu_temple: "교회",
  synagogue: "교회",
  amusement_park: "놀이공원",
  water_park: "놀이공원",
  movie_theater: "영화 극장",
  stadium: "영화 극장",
  event_venue: "영화 극장",
  convention_center: "영화 극장",
  video_arcade: "오락실",
  night_club: "클럽",
  dance_hall: "클럽",
  karaoke: "노래방",
  casino: "카지노",
  hotel: "숙소",
  resort_hotel: "숙소",
  motel: "숙소",
  guest_house: "여관",
  bed_and_breakfast: "여관",
  hostel: "여관",
  inn: "여관",
  campground: "숙박시설",
  lodging: "숙박시설",
  shopping_mall: "백화점",
  department_store: "백화점",
  supermarket: "마트",
  grocery_store: "마트",
  convenience_store: "마트",
  market: "마트",
  clothing_store: "의류",
  shoe_store: "의류",
  jewelry_store: "악세사리",
  gift_shop: "기념품",
  book_store: "도서",
  electronics_store: "전자제품",
  home_goods_store: "생활용품",
  sporting_goods_store: "스포츠용품점",
  florist: "꽃집",
  drugstore: "드럭스토어",
  bicycle_store: "자전거매장",
  furniture_store: "가구매장",
  pet_store: "펫숍",
};

const hasKorean = (value: string) => /[ㄱ-ㅎ가-힣]/.test(value);

export const resolveMiddleCategory = (rawCategory: string) => {
  if (!rawCategory) return "";
  if (hasKorean(rawCategory)) return rawCategory;
  return PLACE_TYPE_TO_MIDDLE_CATEGORY[rawCategory] ?? rawCategory;
};
